services:
  mysql:
    image: mysql:8.4
    container_name: ps-mysql
    environment:
      MYSQL_DATABASE: performance_sports
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_pass
      MYSQL_ROOT_PASSWORD: root_pass
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - ps_mysql_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  ps_mysql_data:
